
baseURL: http://google.com
testClass: googleServiceTests

requiredTests: [ vipTest ]

possiblePrecedencesInOrder: [ primary, secondary ]


proxies:
    http: http://127.0.0.1:8888
    https: http://127.0.0.1:8888


tests:
    vipTest:
        URI: /
        precedence: primary
        baseUrl: baseURL